name: Build and Push to ECR

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Log in to ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin 165066919303.dkr.ecr.us-east-2.amazonaws.com

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Tag image
        run: docker tag my-app:latest 165066919303.dkr.ecr.us-east-2.amazonaws.com/rl/env_rollout

      - name: Push image to ECR
        run: docker push 165066919303.dkr.ecr.us-east-2.amazonaws.com/rl/env_rollout
